In [1]:
from py_api import NIStreamer
import numpy as np

In [2]:
my_exp = NIStreamer()

In [3]:
# Add cards

In [3]:
fast_ao_card = my_exp.add_card(
    card_type='AO',
    max_name='PXI1Slot3',
    samp_rate=1e6,
    trig_mode='prim',
    trig_line='PXI_Trig0',
    ref_clk_mode='prim',
    ref_clk_line='PXI_Trig7',
    ref_clk_rate=10e6
)

slow_ao_card = my_exp.add_card(
    card_type='AO',
    max_name='PXI1Slot4',
    samp_rate=250e3,
    trig_mode='sec',
    trig_line='PXI_Trig0',
    ref_clk_mode='sec',
    ref_clk_line='PXI_Trig7',
    ref_clk_rate=10e6
)

do_card = my_exp.add_card(
    card_type='DO',
    max_name='PXI1Slot6',
    samp_rate=10e6,
    samp_clk_src='PXI_Trig7',
    trig_mode='sec',
    trig_line='PXI_Trig0'
)

In [5]:
# Add channels

In [4]:
bfield_grad = slow_ao_card.add_chnl(
    chan_idx=0
)
mot_aom_pwr = fast_ao_card.add_chnl(
    chan_idx=0
)
mot_shutter = do_card.add_chnl(
    port_idx=0,
    line_idx=0
)

In [5]:
slow_ao_card[0]

In [6]:
do_card['port0/line0']

In [7]:
my_exp.clear_edit_cache()

In [5]:
tau_num = 100
tau_arr = np.linspace(0.5e-3, 10e-3, tau_num)

mot_pwr_num = 10
mot_pwr_arr = np.linspace(0, 1, mot_pwr_num)

buf_time = 100e-6

# Experiment logic script
t = 0

for mot_pwr in mot_pwr_arr:
    for tau in tau_arr:
        
        t += buf_time  # Safety buffer
        
        mot_aom_pwr.sine(
            t=t, dur=tau,
            amp=mot_pwr, freq=100e3,
        )
        
        mot_shutter.go_high(t=t)
        mot_shutter.go_low(t=t+tau)
        
        t += (tau + buf_time)

bfield_grad.sine(
    t=0, dur=t + 1e-3,
    amp=0.5, dc_offs=0.5,
    freq=10e3
)

5.451000000000021

In [8]:
mot_shutter.go_high(t=5.5)

In [8]:
my_exp.compile()

5.451

In [19]:
my_exp.stream_exp()

In [20]:
my_exp.reset_all()

In [ ]:
# Check behavior of status flags

In [10]:
my_exp._exp.is_edited()

True

In [11]:
my_exp._exp.is_compiled()

True

In [11]:
my_exp._exp.is_fresh_compiled()

True

In [12]:
my_exp._exp.compiled_stop_time()

5.5000001

In [18]:
mot_aom_pwr.calc_signal()

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [22]:
mot_shutter.calc_signal()

array([1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [19]:
bfield_grad.calc_signal()

array([5.00000000e-01, 6.69531685e-01, 8.18978455e-01, 9.30634914e-01,
       9.91272793e-01, 9.93708147e-01, 9.37652450e-01, 8.29746787e-01,
       6.82775056e-01, 5.14149429e-01, 3.43847478e-01, 1.92045373e-01,
       7.67275548e-02, 1.15560623e-02, 4.25195320e-03, 5.56805667e-02,
       1.59749004e-01, 3.04127974e-01, 4.71712475e-01, 6.42648283e-01,
       7.96684131e-01, 9.15570941e-01, 9.85223845e-01, 9.97390860e-01,
       9.50630523e-01, 8.50482668e-01, 7.08812106e-01, 5.42402962e-01,
       3.70970215e-01, 2.14824005e-01, 9.24634293e-02, 1.83849046e-02,
       1.36473031e-03, 4.34193364e-02, 1.39566391e-01, 2.78415070e-01,
       4.43515564e-01, 6.15307935e-01, 7.73439438e-01, 8.99175769e-01,
       9.77620579e-01, 9.99480280e-01, 9.62165090e-01, 8.70095848e-01,
       7.34180268e-01, 5.70520666e-01, 3.98506274e-01, 2.38516141e-01,
       1.09504766e-01, 2.67565051e-02, 7.47865209e-05, 3.26206717e-02,
       1.20538354e-01, 2.53411969e-01, 4.15499590e-01, 5.87598222e-01,
      

In [16]:
my_exp._exp.calc_signal(
    dev_name='PXI1Slot3',
    t_start=0,
    t_end=5.451,
    nsamps=1000,
    require_streamable=True,
    require_editable=False,
)

PanicException: There is no channel with streamable=true, editable=false

In [15]:
my_exp._exp.calc_signal(
    dev_name='PXI1Slot6',
    t_start=0,
    t_end=5.451,
    nsamps=1000,
    require_streamable=False,
    require_editable=True,
)

PanicException: There is no channel with streamable=false, editable=true

In [16]:
my_exp._exp.device_compiled_channel_names(
    dev_name='PXI1Slot3',
    require_streamable=False,
    require_editable=True,
)

['ao0']

In [17]:
['ao0'].index('ao0')

0

In [14]:
my_exp._exp.device_compiled_channel_names(
    dev_name='PXI1Slot6',
    require_streamable=False,
    require_editable=True,
)

['port0/line0']

In [15]:
my_exp._exp.device_compiled_channel_names(
    dev_name='PXI1Slot6',
    require_streamable=True,
    require_editable=False,
)

['port0']

In [ ]:
iplot(
    [ao1, ao2, ao10]
)

### Plotly tests

In [24]:
import plotly.graph_objects as go